endpoints:
 enabled: true
 health:
  enabled: true

spring.jpa.database: H2
spring.jpa.show-sql: true
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto : update
spring.data.jpa.repositories.enabled : true
spring.jpa.generate-ddl: true

spring.datasource.url : jdbc:h2:mem:cloudshaala;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username : sa
spring.datasource.password : 
spring.datasource.driverClassName : org.h2.Driver
spring.h2.console.enabled: true

