endpoints:
 enabled: true
 health:
  enabled: true


spring.jpa.show-sql: true
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect


spring.datasource.url : jdbc:mysql://cloudshaala.com:3306/cloudshaala
spring.datasource.username : cloudshaala
spring.datasource.password : cloudshaala
spring.datasource.driverClassName : com.mysql.jdbc.Driver
spring.h2.console.enabled: true
